### Test Error Interceptor
GET http://localhost:8386/error

### Register User
POST http://localhost:8386/api/v1/auth/register
Content-Type: application/json

{
    "username": "johndoe",
    "email": "johndoe@example.com",
    "password": "securepassword123"
}
